language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
- npm install
jobs:
  include:
    - stage: Test & Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    - stage: Build
      script: npm run build
branches:
  only:
    - master
