language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
- npm install
script:
  - npm test
  - npm run build
jobs:
  include:
    - stage: Produce Coverage
      node_js: node
script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
branches:
  only:
  - master